SELECT P.PRODUCT_CODE, SUM(A.SALES_AMOUNT * P.PRICE) AS SALES
FROM PRODUCT AS P
         INNER JOIN OFFLINE_SALE AS A
                    ON P.PRODUCT_ID = A.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE;