SELECT
  TO_CHAR(OS.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE
  , OS.PRODUCT_ID
  , OS.USER_ID
  , OS.SALES_AMOUNT
FROM ONLINE_SALE OS
WHERE 1=1
  AND TO_CHAR(OS.SALES_DATE, 'YYYYMM') = '202203'

UNION ALL

SELECT
  TO_CHAR(OS.SALES_DATE, 'YYYY-MM-DD') AS SALES_DATE
  , OS.PRODUCT_ID
  , NULL AS "USER_ID"
  , OS.SALES_AMOUNT
FROM OFFLINE_SALE OS
WHERE 1=1
  AND TO_CHAR(OS.SALES_DATE, 'YYYYMM') = '202203'

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID